### PR TITLE
Adding NewRelic Service

### PR DESCRIPTION
**Pull request by igorbrites**

### CODE REVIEW

**Comment by LectorRSS** [comment]
This keep session open if Franz is closed?

**Comment by igorbrites** [comment]
@LectorRSS yes it does, for two weeks (default behavior of NewRelic Sessions). I'm using it everyday.

**Comment by LectorRSS** [comment]
Nice, i install it

**Comment by fazlerabbi37** [comment]
I have been using this for 3 days and it seems to be working perfectly. Hoping to give you more feedback in coming days.

**Pull request closed without merging**
