### PR TITLE
WIP: Adding Microsoft Teams Plugin

### PR DESCRIPTION
**Pull request by janmattfeld**
### This is a – currently non-functional – plugin prototype for Microsoft Teams.

The Microsoft Teams web app requires a custom user agent, mimicking a current desktop browser. Additionally, it mustn't include the term `electron`, which breaks the app [1].

For testing, the user agent can be set via Network conditions in the Developer Tools. The plugin then works as expected. E.g. the user agent string for Chrome 52 on Windows works fine `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2725.0 Safari/537.36` 

franz-teams

It should be possible to set the user agent in the `webviewOptions` of the plugin's `package.json` [2], like I did in this pull request. However, the new webview setting [3] is ignored by Franz. I opened an additional issue about this [#263].

[1] https://github.com/webcatalog/webcatalog/issues/28
[2] https://github.com/meetfranz/plugins/blob/develop/docs/configuration.md
[3] https://electron.atom.io/docs/api/webview-tag/#useragent

### CODE REVIEW

**Comment by alcmoraes** [comment]
+1

**Comment by PLanB2008** [comment]
+1

**Comment by marklahn** [comment]
Very exciting to see this plugin as my company has just switched from Google to Office365, and need to replace hangouts with MS Teams. Thank you for making this plugin, hope it'll be functional soon. :)

**Comment by tamassandor-planorama** [comment]
+1

**Comment by thomas-burko** [comment]
+1

**Comment by cduranleau** [comment]
+1

**Comment by xradeon** [comment]
+1

**Comment by mitsut** [comment]
+1

**Comment by uldiskarlovskis** [comment]
+1

**Comment by scheckley** [comment]
+1

**Comment by marklahn** [comment]
I gave up and switched to Rambox, feels like development for Franz has come to a halt.

**Comment by fullvirtue** [comment]
+1

**Comment by gerritjanf** [comment]
+1

**Comment by sguenat** [comment]
+1

**Comment by bviktor** [comment]
Thanks for the tip @marklahn Rambox works fine!

**Comment by larry-xmos** [comment]
+1

**Pull request closed without merging**
