### PR TITLE
Add Mastodon plugin

### PR DESCRIPTION
**Pull request by j0k3r**
It adds a [Mastodon](https://github.com/tootsuite/mastodon) plugin.

It asks for the Mastodon url (even if the label name is `Team Mastodon`, can I translate it somewhere?) before adding the service.

The URL validation is pretty simple, it just retrieve the `URL/about/more` url of the Mastodon instance and check that the repo of Mastodon exist in the response. I didn't find a better and faster way to validate that url.

capture du 2017-04-11 17-41-56

Badge and sound are not handled since I don't know if this is enabled on Mastodon.

### CODE REVIEW

**Comment by j0k3r** [comment]
And for those who wants to test the plugin right away, here is a zip file to unzip in your plugin folder:
 [mastodon.zip](https://github.com/meetfranz/plugins/files/919442/mastodon.zip)

**Comment by gustavi** [comment]
Some news ?

**Comment by arthurlacoste** [comment]
I have tried this plugin, and is work very well ! 👍

**Comment by tamy0612** [comment]
I have tried this, and it doesn't work for several instances which have annoying link to their own forked repository (Ex: [Pawoo.net](https://pawoo.net/about/more)).

I know it's not a great solution, but I think the following modification can help us.

```diff
- if (/github\.com\/tootsuite\/mastodon/i.test(resp)) {
+ if (/github\.com\/[a-zA-Z0-9\-]\/mastodon/i.test(resp)) {
    resolve();
```

Anyway, the plugin is really nice ;)  Thx!

**Comment by j0k3r** [comment]
Closing as it won't be merged ever.

**Pull request closed without merging**
