### PR TITLE
Threema Web Support

### PR DESCRIPTION
**Pull request by apeltzer**
This adds support for Threema Web.

### CODE REVIEW

**Comment by KReguieg** [comment]
I had the same idea, very nice! :)

**Comment by JohannesRegner** [comment]
The plugin seems not to work? Cant connect to Threema, its stopps always on 60%. If you open the threema webapp in Chrome it works...

**Comment by apeltzer** [comment]
Could be also related to that Franz is using an older Electron version in the public version. They also don't seem to update / integrate pull requests too frequently unfortunately. Lots of services out there, that could just be integrated.

**Comment by marcoep** [comment]
Just tried it and got the same problem as @JohannesRegner. Could it be that WebRTCs are not enabled in the included browser?

**Comment by apeltzer** [comment]
Fair point! I guess - since this is something new that was recently introduced in ThreemaWeb-  thats the main cause. In the beginning Threema Web didn't support/use WebRTC as far as I remember

**Comment by marcoep** [comment]
So, does this mean, that we will never get a Threema plugin?

**Comment by apeltzer** [comment]
Not necessarily. When the Franz developers add webrtc support to the next version, we might see it working again

**Pull request closed without merging**
