### PR TITLE
Add FastMail to Franz

### PR DESCRIPTION
**Pull request by pluma**
This provides Franz integration for [FastMail](https://fastmail.com). The notifications tab shows the number of mails in the inbox.

This isn't entirely foolproof because it relies on the inbox being in the sidebar but it's sufficiently reliable that I'm using it in lieu of Thunerbird now. The icon is based on a vectorised version of the official logo as used in the website's bookmark icon.

### CODE REVIEW

**Comment by agustif** [comment]
I tried to replicate your commit in my instance but I am missing something, I hope it gets merged to master soon enough! Thanks for the work!

**Comment by pluma** [comment]
@agustif I'm not sure what you mean. I'm using the plugin locally as we speak.

The fix in the second commit just patches FM's logic for opening links from emails to not use a popup and instead trigger a regular link click. If someone knows a better solution, I'm game.

**Comment by agustif** [comment]
Well, I meant I tried using it locally on my machine with no luck, dont know what got wrong...

**Comment by pluma** [comment]
Can you clarify what goes wrong exactly? Did you copy the folder into your Franz plugins folder (the actual plugins folder inside your Franz settings folder, not the Franz settings folder itself which Franz opens when you click on "open Franz plugins directory")? Are other plugins from this repo working for you?

**Comment by samhains** [comment]
hey! this works perfectly! can we have this merged in?

**Comment by samhains** [comment]
@pluma  thanks a lot!

**Comment by pluma** [comment]
The only problem I can't figure out is how to make the pop-up links work (e.g. view raw message, open another user's inbox), so they open in the browser (which complains about not being logged in, of course). But Slack and Skype have the same problem, so this shouldn't be a blocker.

**Pull request closed without merging**
